name: Build

on:
  push:
    branches:
      - 16.0


jobs:
  build:
    name: Upload coverage reports to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
