name: Build

on:
  push:
    branches:
      - 16.0


jobs:
  build:
    name: Upload coverage reports to Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
